name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ".tests/split_before_each_uppercases_test.py"
      id: tests-split-before-each-uppercases-test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-SPLIT-BEFORE-EACH-UPPERCASES-TEST-PY_RESULTS: "${{steps.tests-split-before-each-uppercases-test-py.result}}"
      with:
        runners: tests-split-before-each-uppercases-test-py
